# Generated by Django 3.2.8 on 2021-10-29 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque', models.IntegerField()),
                ('vendedor_origem', models.CharField(max_length=100)),
                ('data_compra', models.DateField()),
                ('data_validade', models.DateField()),
                ('quantidade_picoles', models.IntegerField()),
                ('preco_lote', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Picole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('sabor', models.CharField(max_length=100)),
                ('calorias', models.IntegerField()),
                ('peso', models.FloatField()),
                ('temperatura_ideal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateField()),
                ('preco', models.FloatField()),
                ('local', models.CharField(max_length=100)),
                ('metodo_pagamento', models.CharField(max_length=100)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_venda.lote')),
                ('tipo_picole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_venda.picole')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='picole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_venda.picole'),
        ),
    ]
